version: '3.8'

services:
  tickety_db:
    image: postgres:latest
    container_name: tickety_db
    environment:
      POSTGRES_DB: tickety
      POSTGRES_USER: tickety
      POSTGRES_PASSWORD: password
    volumes:
      - tickety_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KEYCLOAK_DATABASE_HOST: tickety_db
      KEYCLOAK_DATABASE_PORT: 5432

      KEYCLOAK_DATABASE_NAME: tickety
      KEYCLOAK_DATABASE_USER: tickety
      KEYCLOAK_DATABASE_PASSWORD: password
    depends_on:
      - tickety_db
    ports:
      - "8000:8080"

  rabbitmq:
    container_name: tickety-rabbitmq
    image: bitnami/rabbitmq:3.13.2
    network_mode: host
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      RABBITMQ_LOAD_DEFINITIONS: "true"
      # definition is set with -> user: password
      RABBITMQ_DEFINITIONS_FILE: /etc/rabbitmq/definitions.json
      RABBITMQ_PLUGINS: rabbitmq_shovel rabbitmq_shovel_management rabbitmq_delayed_message_exchange
      RABBITMQ_COMMUNITY_PLUGINS: https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez
    volumes:
      - ./scripts/configs/rabbitmq-definition.json:/etc/rabbitmq/definitions.json
      - tickety_rabbitmq:/bitnami/rabbitmq/mnesia


volumes:
  tickety_data: {}
  tickety_rabbitmq: {}
