version: '3.8'

services:
  tickety_db:
    image: postgres:latest
    container_name: tickety_db
    environment:
      POSTGRES_DB: tickety
      POSTGRES_USER: tickety
      POSTGRES_PASSWORD: password
    volumes:
      - tickety_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: password

      KEYCLOAK_DATABASE_HOST: tickety_db
      KEYCLOAK_DATABASE_PORT: 5432

      KEYCLOAK_DATABASE_NAME: tickety
      KEYCLOAK_DATABASE_USER: tickety
      KEYCLOAK_DATABASE_PASSWORD: password
    depends_on:
      - tickety_db
    ports:
      - "8000:8080"

volumes:
  tickety_data:
